export const config = {
  NETWORK_NAME: process.env.NEXT_PUBLIC_NETWORK_NAME!,
  CELOSTRIALS_ADDRESS: process.env.NEXT_PUBLIC_CELOSTRIALS_ADDRESS!,
  CARBONIZED_ADDRESS: process.env.NEXT_PUBLIC_CARBONIZED_ADDRESS!,
  RARITY_URL: process.env.NEXT_PUBLIC_RARITY_URL!,
  NETWORK_EXPLORER_URL: process.env.NEXT_PUBLIC_NETWORK_EXPLORER_URL!,
  HOST_URL: process.env.NEXT_PUBLIC_HOST_URL!,
}
