export const config = {
  NETWORK_NAME: process.env.NEXT_PUBLIC_NETWORK_NAME!,
  CELOSTRIALS_ADDRESS: process.env.NEXT_PUBLIC_CELOSTRIALS_ADDRESS!,
  RARITY_URL: process.env.NEXT_PUBLIC_RARITY_URL!,
}
