/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICarbonizer, ICarbonizerInterface } from "../ICarbonizer";

const _abi = [
  {
    inputs: [],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICarbonizer__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonizerInterface {
    return new utils.Interface(_abi) as ICarbonizerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICarbonizer {
    return new Contract(address, _abi, signerOrProvider) as ICarbonizer;
  }
}
